server:
  port: 80
logging:
  level:
    edu.haizi.springboot_springmvc: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mysql:///:3306/springboot
      username: root
      password: 110417
mybatis:
  configuration:
    map-underscore-to-camel-case: true

